<a href="https://colab.research.google.com/github/rafio1020/phitron-ai-ml/blob/main/module_2_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def welcome_message():
  print("Hello Hi")

In [ ]:
welcome_message()

Hello Hi

In [ ]:
def welcome_message(user="None"):
  print(f"Hello {user}")

In [ ]:
welcome_message()
welcome_message("Rafio")

Hello None
Hello Rafio

In [ ]:
def adder(a,b):
  """
  add two numbers
  a-->int
  b-->int
  """
  sum=a+b
  return sum

In [ ]:
m = adder(10,30) * 5
print(m)
help(adder)

200
Help on function adder in module __main__:

adder(a, b)
    add two numbers
    a-->int
    b-->int

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

Different type of Argument
1.   Positional Argument

In [ ]:
def adder(a,b,c):
  print(f"{a},{b},{c}")

adder(10,20,30)

10,20

In [ ]:
def adder(*args):
  for i in args:
    print(i)

adder(10,20,23,40)

10
20
23
40




2.   Keyword Argument

In [ ]:
def adder(a,b,c):
  print(f"{a},{b},{c}")

adder(a=10,c=40,b=12)

10,12,40

In [ ]:
def adder(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}: {value}")

adder(a=10,b=20,c=40,n_estimator=40)

a: 10
b: 20
c: 40
n_estimator: 40

Return type of a function

In [ ]:
def adder(a,b):

  sum=a+b
  return sum
print(type(adder(20,29)))

<class 'int'>

In [ ]:
def adder(a,b):

  sum=a+b
  return sum
print(type(adder(20.2,29)))

<class 'float'>

In [ ]:
def welcome_message(user="None"):
  return f"Hello {user}"
print(type(welcome_message("Rafio")))

<class 'str'>

In [ ]:
def adder(a,b):

  sum=a+b
  return sum,a,b
print(type(adder(20.2,29)))

<class 'tuple'>

Iterator

In [ ]:
s = {10,20,30,40}
s_iter = iter(s)
print(type(s_iter))
print(s_iter)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print()
for i in s:
  print(i)

<class 'set_iterator'>
<set_iterator object at 0x7ea3fbe09180>
40
10
20
30

40
10
20
30

Generator

In [ ]:
lst = [x for x in range(500)]
def data_loader(chunk_size,lst):
  for i in range(0,len(lst),chunk_size):
    yield lst[i:i+chunk_size]

x=data_loader(10,lst)
print(x)
print(next(x))
print(next(x))

<generator object data_loader at 0x7ea3fbe0c7c0>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
import pandas as pd

df = pd.DataFrame({'temperature(F)':[32,212,98.6,68]})
df

df['temperature(C)'] = df['temperature(F)'].apply(lambda x:(x-32)*5/9)
df

   temperature(F)  temperature(C)
0            32.0             0.0
1           212.0           100.0
2            98.6            37.0
3            68.0            20.0

In [ ]:
import pandas as pd

df=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
df
df['A']=df['A'].map(lambda x:x**0.5)
df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [ ]:
import pandas as pd

df= pd.DataFrame({'total_spent':[120,500,340,200]})
df['is_high_value']=df['total_spent'].apply(lambda x:1 if x>200 else 0)
df

   total_spent  is_high_value
0          120              0
1          500              1
2          340              1
3          200              0